version: '3.8'

volumes:
  postgres_data:

services:

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - .env
    ports:
      - 5432:5432

  backend:
    image: yasuzuko/foodgram-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./static:/app/static:rw
      - ./media:/app/media:rw

  frontend:
    build:
      context: ../foodgram-project-react/frontend
      dockerfile: Dockerfile
    volumes:
      - ../foodgram-project-react/frontend/:/app/result_build/
  
  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./foodgram-project-react/infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
      - ../foodgram-project-react/frontend/build:/usr/share/nginx/html/
      - ../foodgram-project-react/docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../foodgram-project-react/docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - backend

