version: '3'

services:
  web:
    # production:
    # image: foodgram-img:latest
    restart: unless-stopped

    # dev:
    build: .
    restart: always

    volumes:
      - ./static:/app/static:rw
      - ./media:/app/media:rw
      - ./:/app

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
    depends_on:
      - web
    ports:
      - 80:80
